<?php
/*
 WARNING: DO NOT edit this file under any circumstances.
 Please do all PHP modifications via the Custom Code admin menu.
*/

/**
 * This file calls the init.php file for both Genesis and Prose.
 *
 * It initializes the Genesis framework, and loads the Prose library as well.
 *
 * This file is a core Prose file and should not be edited.
 *
 * @author   StudioPress
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.studiopress.com/themes/genesis
 */

/** Start the engine */
require_once( get_template_directory() . '/lib/init.php' );
require_once( get_stylesheet_directory() . '/lib/init.php' );

prose_create_custom_php();